apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-worker-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sync-worker-role
rules:
- apiGroups: ["poc.gitrenderer.com"]
  resources: ["appconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sync-worker-binding
subjects:
- kind: ServiceAccount
  name: sync-worker-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: sync-worker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-worker
  labels:
    app: sync-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync-worker
  template:
    metadata:
      labels:
        app: sync-worker
    spec:
      serviceAccountName: sync-worker-sa
      containers:
      - name: sync-worker
        image: resource-renderer-sync-worker:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: repo-volume
          mountPath: /var/lib/sync-worker/repo
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "dbserver1.public.app_configs"
        - name: NAMESPACE
          value: "default"
        - name: RENDER_TARGET
          value: "git"
      volumes:
      - name: repo-volume
        emptyDir: {}
